name: koboldExc
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas=0.7.0
  - python=3.8.2
  - rasterio=1.1.3
  - seaborn
  - jupyter
  - jupyterlab
  - descartes=1.1.0
  - matplotlib
  - pandas=1.0.1
  - pylint
  - sphinx
  - twine
